### ISSUE TITLE
Dockbarx 0.91.4 doesn't work on Xubuntu 14.04

### ISSUE THREAD

**Issue by KabbAmine** [M7S/dockbarx#15]
Hi.

I have erros when I try to execute dockbarx:
```
DockbarX 0.91.4
DockbarX init
DockbarX reload
Traceback (most recent call last):
  File "/usr/bin/dockx", line 1439, in <module>
    dockx = DockX(monitor)
  File "/usr/bin/dockx", line 508, in __init__
    self.dockbar.load()
  File "/usr/lib/pymodules/python2.7/dockbarx/dockbar.py", line 550, in load
    self.reload(tell_parent=False)
  File "/usr/lib/pymodules/python2.7/dockbarx/dockbar.py", line 626, in reload
    self.__on_window_opened(self.screen, window)
  File "/usr/lib/pymodules/python2.7/dockbarx/dockbar.py", line 810, in __on_window_opened
    self.__add_window(window)
  File "/usr/lib/pymodules/python2.7/dockbarx/dockbar.py", line 957, in __add_window
    window=window)
  File "/usr/lib/pymodules/python2.7/dockbarx/dockbar.py", line 882, in __make_groupbutton
    group.add_window(window)
  File "/usr/lib/pymodules/python2.7/dockbarx/groupbutton.py", line 359, in add_window
    window = Window(wnck_window, self)
  File "/usr/lib/pymodules/python2.7/dockbarx/windowbutton.py", line 76, in __init__
    self.item = WindowItem(self, group)
  File "/usr/lib/pymodules/python2.7/dockbarx/windowbutton.py", line 343, in __init__
    self.update_show_state()
  File "/usr/lib/pymodules/python2.7/dockbarx/windowbutton.py", line 457, in update_show_state
    window.monitor != self.group_r().monitor):
AttributeError: Window instance has no attribute 'monitor'
```

I've installed dockbarx form the `ppa` (With `--no-install-recommends`) and `dockmanager` & `dockmanager-daemon` manually.

The previous versions worked well and I had just one issue (#5) that should be fixed now.

**Comment by xuzhen** [comment]
I have fixed this bug in my fork: https://github.com/xuzhen/dockbarx/commit/73cb0161cdeed82ed396202bb1c2ae6db65cb950
You can modify those files yourself.

If you don't have multiple monitors, you can just simply disable "ignore windows on other monitors" option by using the following command
`gconftool -s /apps/dockbarx/show_only_current_monitor -t bool false`

**Comment by KabbAmine** [comment]
@xuzhen I'm already using your fork, and it works well.

**Comment by KabbAmine** [comment]
Hi @xuzhen

I'm still using your fork on my xubuntu, and its working as it should.
But now that I have a 2nd monitor, it will be more than great to have the option `show_only_current_monitor` working as expected. Is there any way to implement that in your fork?

**Comment by xuzhen** [comment]
Hi @KabbAmine 
I have commited some patches into my fork to fix that. Please try it.

**Comment by KabbAmine** [comment]
Just awesome @xuzhen The multi-monitor option works well.
Thank you very much :smiley:
